ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "sleeperUsername" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "sleeperLeagueId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "sleeperDraftId" TEXT;
